version: "3.0"
services:
    redis:
      image: redis:alpine
      container_name: nextpayday-redis

    mysql:
      image: mysql:5.6
      container_name: nextpayday-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=nextpayday
        - MYSQL_USER=nextpayday
        - MYSQL_PASSWORD=nextpayday
      ports:
        - "8082:3306"

    webserver:
      build: docker/nginx
      container_name: nextpayday-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      container_name: nextpayday-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

